### ISSUE TITLE
Potentially dangerous method.

### ISSUE THREAD

**Issue by ryantheleach** [lm9/iitc-plugins#2]
https://github.com/ekuinox/iitc-plugins/blob/1383a64cc32f5ad19745eabd8ddaeeb7d689cc89/src/Near8.js#L78

For maintainability sake, and for less chance of getting yourself banned for hammering, it should check whether the portal details are fresh, and use IITC's inbuilt methods to pull the data.

see https://gist.github.com/ryantheleach/e7d730e43d648bb59baff2698499c743#file-highlight-plrtals-almost-to-L54

**Comment by ekuinox** [comment]
私はもうIngressほとんどやっていなくて、このプラグインも利用していないのでメンテする気がありません。xhrをかけているプラグインは削除しておきます。
